# Generated by Django 4.2.10 on 2026-02-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_job_required_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("oa_round", "OA Round"),
                    ("tech_round", "Tech Round"),
                    ("hr_round", "HR Round"),
                    ("offer_received", "Offer Received"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="applied",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this job"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "candidate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="jobs_savedj_user_id_151869_idx",
                    )
                ],
                "unique_together": {("user", "job")},
            },
        ),
    ]
