# Generated by Django 4.2.27 on 2026-02-05 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_application_status_savedjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, help_text="Interview duration in minutes"
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Interview"),
                            ("video", "Video Interview"),
                            ("in_person", "In-Person Interview"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or meeting link (Zoom, Google Meet, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or instructions for the candidate",
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="jobs.application",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_datetime"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_datetime", "status"],
                        name="jobs_interv_schedul_8026f8_idx",
                    ),
                    models.Index(
                        fields=["application", "status"],
                        name="jobs_interv_applica_1c625c_idx",
                    ),
                ],
            },
        ),
    ]
