# Generated by Django 4.2.27 on 2026-02-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_candidateprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="college_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="github_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="leetcode_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="passout_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
